name: notify push
on:
  push:
jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: install requests
      run: pip install -r .github/workflows/requirements.txt
    - name: send message to discord
      env:
        github: ${{ toJSON(github) }}
        token: ${{ secrets.TOKEN }}
      run: |
        cd .github/workflows
        python main.py
        cd ../../
